const CATALOG = [
    {
        id: 'car1',
        className: ' active',
        img: 'images/car_1-5.png',
        carBrands: ['ГАЗель', 'Isuzu', 'Kia', 'Mitsubishi'],
        carLength: 'от 3 м до 5 м',
        carVolume: 'от 9 до 20 куб.м.',
        carryingCapacity: 'от 1.5 до 2 т',
        price: '15 руб./км',
    },
    {
        id: 'car3',
        className: ' ',
        img: 'images/car_3.png',
        carBrands: ['ГАЗ "Бычок"','Валдай', 'Isuzu', 'Hino', 'Mazda'],
        carLength: 'от 4,5 м до 6,5 м',
        carVolume: 'от 18 до 30 куб.м.',
        carryingCapacity: 'от 3 до 4 т',
        price: '17 руб./км',
    },
    {
        id: 'car5',
        className: '',
        img: 'images/car_3.png',
        carBrands: ['Hino', 'Volvo', 'Камаз', 'Isuzu'],
        carLength: 'от 4,5 м до 6,5 м',
        carVolume: 'от 18 до 30 куб.м.',
        carryingCapacity: 'от 3 до 4 т',
        price: '17 руб./км',
    },
    {
        id: 'car10',
        className: ' ',
        img: 'images/car_10.png',
        carBrands: ['Hino', 'Volvo', 'Камаз', 'Isuzu'],
        carLength: 'от 4,5 м до 6,5 м',
        carVolume: 'от 18 до 30 куб.м.',
        carryingCapacity: 'от 3 до 4 т',
        price: '17 руб./км',
    },
    {
        id: 'car20',
        className: ' ',
        img: 'images/car_20.png',
        carBrands: ['ГАЗ "Бычок"', 'Валдай', 'Isuzu', 'Hino', 'Mazda'],
        carLength: 'от 4,5 м до 6,5 м',
        carVolume: 'от 18 до 30 куб.м.',
        carryingCapacity: 'от 3 до 4 т',
        price: '17 руб./км',
    },

];
